version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: npm install
          command: npm ci
      - run:
          name: npm build
          command: npm run build
      - run:
          name: deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
