version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: npm install
          command: npm ci
      - run:
          name: install firebase-tools
          command: npm install --save-dev firebase-tools
      - run:
          name: npm build
          command: npm run build
      - run:
          name: deploy
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
